import http from 'node:http'
import crypto from 'node:crypto'
import mysql from 'mysql2/promise'

const PORT = Number(process.env.PORT || 8790)
const ADMIN_EMAIL = String(process.env.ADMIN_EMAIL || 'diyiwuyan@163.com').toLowerCase()
const SESSION_DAYS = 30
const db = mysql.createPool({ host: process.env.DB_HOST, port: Number(process.env.DB_PORT || 3306), user: process.env.DB_USER, password: process.env.DB_PASSWORD, database: process.env.DB_NAME, waitForConnections: true, connectionLimit: 8, charset: 'utf8mb4' })
const now = () => new Date().toISOString().slice(0, 19).replace('T', ' ')
const uuid = () => crypto.randomUUID()
const hash = (value) => crypto.createHash('sha256').update(String(value)).digest('hex')
const validEmail = (email) => /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(String(email || '').trim())
const validPassword = (value) => typeof value === 'string' && value.length >= 8 && value.length <= 128
const cookie = (token) => `wu_session=${token}; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=${SESSION_DAYS * 86400}`
const parseCookies = (request) => Object.fromEntries((request.headers.cookie || '').split(';').map((part) => part.trim().split('=').map(decodeURIComponent)).filter(([key]) => key))
const normalize = (value, length = 1000) => String(value || '').trim().slice(0, length)
const allowedOrigins = new Set(['https://diyiwuyan.github.io', 'https://ai.abcdabcd.cc', 'https://abcdabcd.cc', 'https://www.abcdabcd.cc'])

function cors(request) {
  const origin = request.headers.origin || ''
  const local = /^http:\/\/(localhost|127\.0\.0\.1)(?::\d+)?$/i.test(origin)
  const cloudbase = /^https:\/\/[a-z0-9-]+(?:\.[a-z0-9-]+)*\.tcb\.qcloud\.la$/i.test(origin)
  return allowedOrigins.has(origin) || local || cloudbase ? { 'Access-Control-Allow-Origin': origin, 'Access-Control-Allow-Credentials': 'true', 'Vary': 'Origin', 'Access-Control-Allow-Headers': 'Content-Type', 'Access-Control-Allow-Methods': 'GET,POST,PATCH,DELETE,OPTIONS' } : { Vary: 'Origin' }
}
function send(response, request, status, data, extra = {}) { response.writeHead(status, { 'Content-Type': 'application/json; charset=utf-8', ...cors(request), ...extra }); response.end(JSON.stringify(data)) }
async function readBody(request) { const parts = []; for await (const part of request) parts.push(part); try { return JSON.parse(Buffer.concat(parts).toString() || '{}') } catch { return {} } }
async function passwordHash(password, salt) { return new Promise((resolve, reject) => crypto.scrypt(password, salt, 64, { N: 16384, r: 8, p: 1 }, (error, derived) => error ? reject(error) : resolve(derived.toString('hex')))) }
async function ensureProfile(userId, inviterId = null) { const [[existing]] = await db.query('SELECT code FROM referral_profiles WHERE user_id = ?', [userId]); if (existing) return existing.code; for (let index = 0; index < 3; index += 1) { const code = 'WU' + crypto.randomBytes(5).toString('hex').toUpperCase(); try { await db.query('INSERT INTO referral_profiles (user_id, code, inviter_id, created_at) VALUES (?, ?, ?, ?)', [userId, code, inviterId, now()]); return code } catch { /* code collision */ } } return null }
async function enrich(user) { const [[points]] = await db.query('SELECT balance FROM user_points WHERE user_id = ?', [user.id]); const [entitlements] = await db.query('SELECT course_id FROM course_entitlements WHERE user_id = ?', [user.id]); const referralCode = await ensureProfile(user.id); return { id: user.id, email: user.email, name: user.name, role: user.role, status: user.status, createdAt: user.created_at || user.createdAt, points: Number(points?.balance || 0), referralCode, unlockedCourses: entitlements.map((item) => item.course_id) } }
async function currentUser(request) { const token = parseCookies(request).wu_session; if (!token) return null; const [[user]] = await db.query('SELECT users.* FROM sessions JOIN users ON users.id = sessions.user_id WHERE sessions.token_hash = ? AND sessions.expires_at > ? AND users.status = "active"', [hash(token), Date.now()]); return user ? enrich(user) : null }
async function createSession(userId) { const token = crypto.randomBytes(32).toString('base64url'); await db.query('INSERT INTO sessions (token_hash, user_id, expires_at, created_at) VALUES (?, ?, ?, ?)', [hash(token), userId, Date.now() + SESSION_DAYS * 86400 * 1000, now()]); return token }
const requireAdmin = async (request, response) => { const user = await currentUser(request); if (!user || user.role !== 'admin') { send(response, request, 403, { message: '无管理员权限' }); return null } return user }

async function register(request, response, body) { const email = normalize(body.email, 190).toLowerCase(); const name = normalize(body.name, 40); const password = String(body.password || ''); if (!validEmail(email)) return send(response, request, 400, { message: '请输入有效邮箱' }); if (!validPassword(password)) return send(response, request, 400, { message: '密码至少 8 位，最多 128 位' }); const [[existing]] = await db.query('SELECT * FROM users WHERE email = ?', [email]); if (existing?.password_hash) return send(response, request, 409, { message: '该邮箱已注册，请直接登录' }); const id = existing?.id || uuid(); const salt = crypto.randomBytes(16).toString('hex'); const encrypted = await passwordHash(password, salt); const role = email === ADMIN_EMAIL ? 'admin' : 'learner'; const time = now(); await db.query('INSERT INTO users (id, email, name, role, status, password_hash, password_salt, created_at, updated_at) VALUES (?, ?, ?, ?, "active", ?, ?, ?, ?) ON DUPLICATE KEY UPDATE name = VALUES(name), role = IF(VALUES(role) = "admin", "admin", role), status = "active", password_hash = VALUES(password_hash), password_salt = VALUES(password_salt), updated_at = VALUES(updated_at)', [id, email, name || email.split('@')[0], role, encrypted, salt, time, time]); await db.query('INSERT IGNORE INTO user_points (user_id, balance, updated_at) VALUES (?, 0, ?)', [id, time]); const invite = normalize(body.inviteCode, 30).toUpperCase(); let inviterId = null; if (!existing && invite) { const [[inviter]] = await db.query('SELECT user_id FROM referral_profiles WHERE code = ?', [invite]); inviterId = inviter?.user_id || null } await ensureProfile(id, inviterId); const [[user]] = await db.query('SELECT * FROM users WHERE id = ?', [id]); const token = await createSession(id); send(response, request, 201, { ok: true, user: await enrich(user) }, { 'Set-Cookie': cookie(token) }) }
async function login(request, response, body) { const email = normalize(body.email, 190).toLowerCase(); const password = String(body.password || ''); const [[user]] = await db.query('SELECT * FROM users WHERE email = ?', [email]); if (!user || !user.password_hash || !crypto.timingSafeEqual(Buffer.from(await passwordHash(password, user.password_salt), 'hex'), Buffer.from(user.password_hash, 'hex'))) return send(response, request, 401, { message: '邮箱或密码不正确' }); if (user.status !== 'active') return send(response, request, 403, { message: '账号不可用，请联系管理员' }); const token = await createSession(user.id); send(response, request, 200, { ok: true, user: await enrich(user) }, { 'Set-Cookie': cookie(token) }) }

async function api(request, response, url) {
  const route = url.pathname.replace(/^\/api\/?/, '')
  if (request.method === 'OPTIONS') { response.writeHead(204, cors(request)); return response.end() }
  if (route === 'health') return send(response, request, 200, { ok: true, service: 'wu-ai-practice-camp-china-api', time: new Date().toISOString() })
  const body = ['POST', 'PATCH'].includes(request.method) ? await readBody(request) : {}
  if (request.method === 'POST' && route === 'auth/password-register') return register(request, response, body)
  if (request.method === 'POST' && route === 'auth/password-login') return login(request, response, body)
  if (request.method === 'POST' && route === 'auth/logout') { const token = parseCookies(request).wu_session; if (token) await db.query('DELETE FROM sessions WHERE token_hash = ?', [hash(token)]); return send(response, request, 200, { ok: true }, { 'Set-Cookie': 'wu_session=; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=0' }) }
  if (request.method === 'GET' && route === 'me') return send(response, request, 200, { user: await currentUser(request) })
  if (route === 'auth/request-code' || route === 'auth/verify-code' || route === 'auth/password-reset') return send(response, request, 501, { message: '国内版当前使用邮箱密码登录；验证码找回正在迁移中。' })
  if (request.method === 'GET' && route === 'referrals') { const user = await currentUser(request); if (!user) return send(response, request, 401, { message: '请先登录' }); const [[profile]] = await db.query('SELECT code FROM referral_profiles WHERE user_id = ?', [user.id]); const [[count]] = await db.query('SELECT COUNT(*) AS count FROM referral_profiles WHERE inviter_id = ?', [user.id]); const [[earned]] = await db.query("SELECT COALESCE(SUM(amount), 0) AS total FROM point_transactions WHERE user_id = ? AND type = 'referral_reward'", [user.id]); return send(response, request, 200, { referralCode: profile?.code, invitedCount: Number(count?.count || 0), earnedPoints: Number(earned?.total || 0), rate: 0.3, windowDays: 30, transactions: [] }) }
  if (request.method === 'POST' && route === 'points/redeem') { const user = await currentUser(request); if (!user) return send(response, request, 401, { message: '请先登录' }); const code = normalize(body.code, 100).toUpperCase(); if (!code) return send(response, request, 400, { message: '请输入兑换码' }); const connection = await db.getConnection(); try { await connection.beginTransaction(); const [[item]] = await connection.query('SELECT * FROM redemption_codes WHERE code_hash = ? FOR UPDATE', [hash(code)]); if (!item || item.status !== 'unused') { await connection.rollback(); return send(response, request, 400, { message: '兑换码不存在或已使用' }) } const time = now(); await connection.query("UPDATE redemption_codes SET status='redeemed', redeemed_by=?, redeemed_at=? WHERE id=?", [user.id, time, item.id]); await connection.query('INSERT INTO user_points (user_id,balance,updated_at) VALUES (?, ?, ?) ON DUPLICATE KEY UPDATE balance=balance+VALUES(balance),updated_at=VALUES(updated_at)', [user.id, item.points, time]); await connection.query('INSERT INTO point_transactions (id,user_id,amount,type,reference_id,note,created_at) VALUES (?, ?, ?, ?, ?, ?, ?)', [uuid(), user.id, item.points, 'redeem_code', item.id, '兑换码充值（积分兑换后不退不换）', time]); await connection.commit(); const [[fresh]] = await db.query('SELECT * FROM users WHERE id=?', [user.id]); return send(response, request, 200, { ok: true, addedPoints: Number(item.points), user: await enrich(fresh) }) } catch (error) { await connection.rollback(); throw error } finally { connection.release() } }
  const unlock = route.match(/^courses\/([^/]+)\/unlock$/)
  if (request.method === 'POST' && unlock) { const user = await currentUser(request); const courseId = ['codex', 'image', 'career', 'works'].includes(unlock?.[1]) ? unlock[1] : ''; if (!user) return send(response, request, 401, { message: '请先登录' }); if (!courseId) return send(response, request, 400, { message: '课程编号无效' }); if (user.unlockedCourses.includes(courseId)) return send(response, request, 200, { ok: true, alreadyUnlocked: true, user }); const connection = await db.getConnection(); try { await connection.beginTransaction(); const [[balance]] = await connection.query('SELECT balance FROM user_points WHERE user_id=? FOR UPDATE', [user.id]); const price = 49.9; if (Number(balance?.balance || 0) < price) { await connection.rollback(); return send(response, request, 400, { message: `积分不足，需要 ${price} 积分，当前只有 ${Number(balance?.balance || 0)} 积分` }) } const time = now(); await connection.query('UPDATE user_points SET balance=balance-?,updated_at=? WHERE user_id=?', [price, time, user.id]); await connection.query('INSERT INTO course_entitlements (id,user_id,course_id,granted_by,granted_at) VALUES (?, ?, ?, ?, ?)', [uuid(), user.id, courseId, 'points', time]); await connection.query('INSERT INTO point_transactions (id,user_id,amount,type,reference_id,note,created_at) VALUES (?, ?, ?, ?, ?, ?, ?)', [uuid(), user.id, -price, 'course_unlock', courseId, `解锁课程：${courseId}`, time]); await connection.commit(); const [[fresh]] = await db.query('SELECT * FROM users WHERE id=?', [user.id]); return send(response, request, 200, { ok: true, courseId, spentPoints: price, user: await enrich(fresh) }) } catch (error) { await connection.rollback(); throw error } finally { connection.release() } }
  if (request.method === 'POST' && route === 'admin/redemption-codes') { const admin = await requireAdmin(request, response); if (!admin) return; const count = Math.max(1, Math.min(200, Math.floor(Number(body.count || 0)))); const points = Number(body.points || 0); if (!Number.isFinite(points) || points <= 0) return send(response, request, 400, { message: '积分面值无效' }); const codes = []; const time = now(); for (let index = 0; index < count; index += 1) { const code = `WU-${crypto.randomBytes(3).toString('hex').toUpperCase()}-${crypto.randomBytes(3).toString('hex').toUpperCase()}-${crypto.randomBytes(3).toString('hex').toUpperCase()}`; await db.query('INSERT INTO redemption_codes (id,code_hash,points,status,created_at,created_by) VALUES (?, ?, ?, "unused", ?, ?)', [uuid(), hash(code), points, time, admin.id]); codes.push({ code, points }) } return send(response, request, 201, { ok: true, codes }) }
  if (request.method === 'POST' && route === 'admin/users') { const admin = await requireAdmin(request, response); if (!admin) return; const email = normalize(body.email, 190).toLowerCase(); const name = normalize(body.name, 40); const password = String(body.password || ''); if (!validEmail(email) || !validPassword(password)) return send(response, request, 400, { message: '请输入有效邮箱和至少 8 位的初始密码' }); const [[exists]] = await db.query('SELECT id FROM users WHERE email=?', [email]); if (exists) return send(response, request, 409, { message: '该邮箱已存在' }); const id = uuid(); const salt = crypto.randomBytes(16).toString('hex'); const encrypted = await passwordHash(password, salt); const time = now(); const points = Math.max(0, Number(body.points || 0)); await db.query('INSERT INTO users (id,email,name,role,status,password_hash,password_salt,created_at,updated_at) VALUES (?, ?, ?, ?, "active", ?, ?, ?, ?)', [id, email, name || email.split('@')[0], body.role === 'admin' ? 'admin' : 'learner', encrypted, salt, time, time]); await db.query('INSERT INTO user_points (user_id,balance,updated_at) VALUES (?, ?, ?)', [id, points, time]); await ensureProfile(id); return send(response, request, 201, { ok: true }) }
  const adminUser = route.match(/^admin\/users\/([^/]+)$/)
  if (adminUser && request.method === 'PATCH') { const admin = await requireAdmin(request, response); if (!admin) return; const [[target]] = await db.query('SELECT * FROM users WHERE id=?', [adminUser[1]]); if (!target) return send(response, request, 404, { message: '用户不存在' }); const status = ['active', 'suspended'].includes(body.status) ? body.status : target.status; const role = ['admin', 'learner'].includes(body.role) ? body.role : target.role; if (target.id === admin.id && status !== 'active') return send(response, request, 400, { message: '不能停用当前管理员' }); const name = normalize(body.name, 40) || target.name; const password = String(body.password || ''); let query = 'UPDATE users SET name=?, role=?, status=?, updated_at=?'; const values = [name, role, status, now()]; if (password) { if (!validPassword(password)) return send(response, request, 400, { message: '新密码至少 8 位' }); const salt = crypto.randomBytes(16).toString('hex'); query += ', password_hash=?, password_salt=?'; values.push(await passwordHash(password, salt), salt) } query += ' WHERE id=?'; values.push(target.id); await db.query(query, values); if (status !== 'active') await db.query('DELETE FROM sessions WHERE user_id=?', [target.id]); return send(response, request, 200, { ok: true }) }
  if (adminUser && request.method === 'DELETE') { const admin = await requireAdmin(request, response); if (!admin) return; if (adminUser[1] === admin.id) return send(response, request, 400, { message: '不能删除当前管理员' }); await db.query("UPDATE users SET status='deleted',updated_at=? WHERE id=?", [now(), adminUser[1]]); await db.query('DELETE FROM sessions WHERE user_id=?', [adminUser[1]]); return send(response, request, 200, { ok: true }) }
  const adminPoints = route.match(/^admin\/users\/([^/]+)\/points$/)
  if (adminPoints && request.method === 'POST') { const admin = await requireAdmin(request, response); if (!admin) return; const amount = Number(body.amount || 0); if (!Number.isFinite(amount) || amount === 0) return send(response, request, 400, { message: '积分调整金额无效' }); const time = now(); await db.query('INSERT INTO user_points (user_id,balance,updated_at) VALUES (?, 0, ?) ON DUPLICATE KEY UPDATE updated_at=VALUES(updated_at)', [adminPoints[1], time]); const [updated] = await db.query('UPDATE user_points SET balance=balance+?,updated_at=? WHERE user_id=? AND balance+? >= 0', [amount, time, adminPoints[1], amount]); if (!updated.affectedRows) return send(response, request, 400, { message: '扣减后积分不能小于 0' }); await db.query('INSERT INTO point_transactions (id,user_id,amount,type,reference_id,note,created_at) VALUES (?, ?, ?, ?, ?, ?, ?)', [uuid(), adminPoints[1], amount, 'admin_adjust', admin.id, normalize(body.note, 100) || '管理员直充', time]); return send(response, request, 200, { ok: true }) }
  const adminCourse = route.match(/^admin\/users\/([^/]+)\/courses(?:\/([^/]+))?$/)
  if (adminCourse && ['POST', 'DELETE'].includes(request.method)) { const admin = await requireAdmin(request, response); if (!admin) return; const courseId = request.method === 'POST' ? normalize(body.courseId, 30) : adminCourse[2]; if (!['codex', 'image', 'career', 'works'].includes(courseId)) return send(response, request, 400, { message: '课程编号无效' }); if (request.method === 'POST') await db.query('INSERT IGNORE INTO course_entitlements (id,user_id,course_id,granted_by,granted_at) VALUES (?, ?, ?, ?, ?)', [uuid(), adminCourse[1], courseId, admin.id, now()]); else await db.query('DELETE FROM course_entitlements WHERE user_id=? AND course_id=?', [adminCourse[1], courseId]); return send(response, request, 200, { ok: true, courseId }) }
  if (request.method === 'GET' && route === 'admin/dashboard') { const admin = await requireAdmin(request, response); if (!admin) return; const [users] = await db.query('SELECT u.id,u.email,u.name,u.role,u.status,u.created_at,COALESCE(p.balance,0) AS points FROM users u LEFT JOIN user_points p ON p.user_id=u.id ORDER BY u.created_at DESC LIMIT 200'); const [submissions] = await db.query('SELECT s.*,u.email AS authorEmail,u.name AS author FROM submissions s JOIN users u ON u.id=s.user_id ORDER BY s.created_at DESC LIMIT 200'); const mapped = await Promise.all(users.map(async (user) => ({ ...user, createdAt: user.created_at, unlockedCourses: (await db.query('SELECT course_id FROM course_entitlements WHERE user_id = ?', [user.id]))[0].map((item) => item.course_id) }))); return send(response, request, 200, { users: mapped, submissions, redemptionCodes: [], stats: { users: mapped.length, submissions: submissions.length, pending: submissions.filter((item) => item.status === 'pending').length } }) }
  return send(response, request, 404, { message: 'API 路径不存在' })
}

http.createServer(async (request, response) => { try { const url = new URL(request.url || '/', 'http://localhost'); if (!url.pathname.startsWith('/api')) return send(response, request, 404, { message: 'Not found' }); await api(request, response, url) } catch (error) { console.error(error); send(response, request, 500, { message: '服务器处理失败' }) } }).listen(PORT, '127.0.0.1', () => console.log(`wu ai china api listening on ${PORT}`))
