import { imagePromptCardAppendix as promptCardAppendix } from './imageCourseContent'

export const imageCourseMedia = {
  "appendix1": [
    "assets/image-course-feishu/appendix1-001.png",
    "assets/image-course-feishu/appendix1-002.png",
    "assets/image-course-feishu/appendix1-003.png"
  ],
  "handbook": [
    "assets/image-course-feishu/handbook-001.png",
    "assets/image-course-feishu/handbook-002.png",
    "assets/image-course-feishu/handbook-003.png",
    "assets/image-course-feishu/handbook-004.png",
    "assets/image-course-feishu/handbook-005.png",
    "assets/image-course-feishu/handbook-006.png",
    "assets/image-course-feishu/handbook-007.png",
    "assets/image-course-feishu/handbook-008.png",
    "assets/image-course-feishu/handbook-009.png",
    "assets/image-course-feishu/handbook-010.png",
    "assets/image-course-feishu/handbook-011.png",
    "assets/image-course-feishu/handbook-012.png",
    "assets/image-course-feishu/handbook-013.png",
    "assets/image-course-feishu/handbook-014.png",
    "assets/image-course-feishu/handbook-015.png",
    "assets/image-course-feishu/handbook-016.png",
    "assets/image-course-feishu/handbook-017.png",
    "assets/image-course-feishu/handbook-018.png",
    "assets/image-course-feishu/handbook-019.png",
    "assets/image-course-feishu/handbook-020.png",
    "assets/image-course-feishu/handbook-021.png",
    "assets/image-course-feishu/handbook-022.png",
    "assets/image-course-feishu/handbook-023.png",
    "assets/image-course-feishu/handbook-024.png",
    "assets/image-course-feishu/handbook-025.png",
    "assets/image-course-feishu/handbook-026.jpg",
    "assets/image-course-feishu/handbook-027.jpg",
    "assets/image-course-feishu/handbook-028.jpg",
    "assets/image-course-feishu/handbook-029.jpg",
    "assets/image-course-feishu/handbook-030.jpg",
    "assets/image-course-feishu/handbook-031.jpg",
    "assets/image-course-feishu/handbook-032.jpg",
    "assets/image-course-feishu/handbook-033.jpg",
    "assets/image-course-feishu/handbook-034.jpg",
    "assets/image-course-feishu/handbook-035.jpg",
    "assets/image-course-feishu/handbook-036.jpg",
    "assets/image-course-feishu/handbook-037.jpg",
    "assets/image-course-feishu/handbook-038.jpg",
    "assets/image-course-feishu/handbook-039.jpg",
    "assets/image-course-feishu/handbook-040.jpg",
    "assets/image-course-feishu/handbook-041.jpg",
    "assets/image-course-feishu/handbook-042.jpg",
    "assets/image-course-feishu/handbook-043.jpg",
    "assets/image-course-feishu/handbook-044.jpg",
    "assets/image-course-feishu/handbook-045.jpg",
    "assets/image-course-feishu/handbook-046.jpg",
    "assets/image-course-feishu/handbook-047.jpg",
    "assets/image-course-feishu/handbook-048.jpg",
    "assets/image-course-feishu/handbook-049.jpg",
    "assets/image-course-feishu/handbook-050.jpg",
    "assets/image-course-feishu/handbook-051.jpg",
    "assets/image-course-feishu/handbook-052.jpg",
    "assets/image-course-feishu/handbook-053.jpg",
    "assets/image-course-feishu/handbook-054.jpg",
    "assets/image-course-feishu/handbook-055.jpg",
    "assets/image-course-feishu/handbook-056.jpg",
    "assets/image-course-feishu/handbook-057.jpg",
    "assets/image-course-feishu/handbook-058.jpg",
    "assets/image-course-feishu/handbook-059.jpg",
    "assets/image-course-feishu/handbook-060.png",
    "assets/image-course-feishu/handbook-061.jpg",
    "assets/image-course-feishu/handbook-062.jpg",
    "assets/image-course-feishu/handbook-063.jpg",
    "assets/image-course-feishu/handbook-064.jpg",
    "assets/image-course-feishu/handbook-065.jpg",
    "assets/image-course-feishu/handbook-066.jpg",
    "assets/image-course-feishu/handbook-067.jpg",
    "assets/image-course-feishu/handbook-068.jpg",
    "assets/image-course-feishu/handbook-069.jpg",
    "assets/image-course-feishu/handbook-070.jpg",
    "assets/image-course-feishu/handbook-071.jpg",
    "assets/image-course-feishu/handbook-072.jpg",
    "assets/image-course-feishu/handbook-073.jpg",
    "assets/image-course-feishu/handbook-074.jpg",
    "assets/image-course-feishu/handbook-075.jpg",
    "assets/image-course-feishu/handbook-076.jpg",
    "assets/image-course-feishu/handbook-077.jpg",
    "assets/image-course-feishu/handbook-078.jpg",
    "assets/image-course-feishu/handbook-079.jpg",
    "assets/image-course-feishu/handbook-080.jpg",
    "assets/image-course-feishu/handbook-081.jpg",
    "assets/image-course-feishu/handbook-082.jpg",
    "assets/image-course-feishu/handbook-083.jpg",
    "assets/image-course-feishu/handbook-084.jpg",
    "assets/image-course-feishu/handbook-085.jpg",
    "assets/image-course-feishu/handbook-086.jpg",
    "assets/image-course-feishu/handbook-087.jpg",
    "assets/image-course-feishu/handbook-088.jpg",
    "assets/image-course-feishu/handbook-089.jpg",
    "assets/image-course-feishu/handbook-090.jpg",
    "assets/image-course-feishu/handbook-091.jpg",
    "assets/image-course-feishu/handbook-092.jpg",
    "assets/image-course-feishu/handbook-093.jpg",
    "assets/image-course-feishu/handbook-094.jpg",
    "assets/image-course-feishu/handbook-095.jpg",
    "assets/image-course-feishu/handbook-096.jpg",
    "assets/image-course-feishu/handbook-097.jpg",
    "assets/image-course-feishu/handbook-098.jpg",
    "assets/image-course-feishu/handbook-099.jpg",
    "assets/image-course-feishu/handbook-100.jpg",
    "assets/image-course-feishu/handbook-101.jpg",
    "assets/image-course-feishu/handbook-102.jpg",
    "assets/image-course-feishu/handbook-103.jpg",
    "assets/image-course-feishu/handbook-104.jpg",
    "assets/image-course-feishu/handbook-105.jpg",
    "assets/image-course-feishu/handbook-106.jpg",
    "assets/image-course-feishu/handbook-107.jpg",
    "assets/image-course-feishu/handbook-108.jpg",
    "assets/image-course-feishu/handbook-109.jpg",
    "assets/image-course-feishu/handbook-110.jpg",
    "assets/image-course-feishu/handbook-111.jpg",
    "assets/image-course-feishu/handbook-112.jpg",
    "assets/image-course-feishu/handbook-113.jpg",
    "assets/image-course-feishu/handbook-114.jpg",
    "assets/image-course-feishu/handbook-115.jpg",
    "assets/image-course-feishu/handbook-116.jpg",
    "assets/image-course-feishu/handbook-117.jpg",
    "assets/image-course-feishu/handbook-118.jpg",
    "assets/image-course-feishu/handbook-119.jpg",
    "assets/image-course-feishu/handbook-120.jpg",
    "assets/image-course-feishu/handbook-121.jpg",
    "assets/image-course-feishu/handbook-122.jpg",
    "assets/image-course-feishu/handbook-123.jpg",
    "assets/image-course-feishu/handbook-124.jpg",
    "assets/image-course-feishu/handbook-125.jpg",
    "assets/image-course-feishu/handbook-126.jpg",
    "assets/image-course-feishu/handbook-127.jpg",
    "assets/image-course-feishu/handbook-128.jpg",
    "assets/image-course-feishu/handbook-129.jpg",
    "assets/image-course-feishu/handbook-130.jpg",
    "assets/image-course-feishu/handbook-131.jpg",
    "assets/image-course-feishu/handbook-132.jpg",
    "assets/image-course-feishu/handbook-133.jpg",
    "assets/image-course-feishu/handbook-134.jpg",
    "assets/image-course-feishu/handbook-135.jpg",
    "assets/image-course-feishu/handbook-136.jpg",
    "assets/image-course-feishu/handbook-137.jpg",
    "assets/image-course-feishu/handbook-138.jpg",
    "assets/image-course-feishu/handbook-139.jpg",
    "assets/image-course-feishu/handbook-140.jpg",
    "assets/image-course-feishu/handbook-141.jpg",
    "assets/image-course-feishu/handbook-142.jpg",
    "assets/image-course-feishu/handbook-143.jpg",
    "assets/image-course-feishu/handbook-144.jpg",
    "assets/image-course-feishu/handbook-145.jpg",
    "assets/image-course-feishu/handbook-146.jpg",
    "assets/image-course-feishu/handbook-147.jpg",
    "assets/image-course-feishu/handbook-148.jpg",
    "assets/image-course-feishu/handbook-149.jpg",
    "assets/image-course-feishu/handbook-150.jpg",
    "assets/image-course-feishu/handbook-151.jpg",
    "assets/image-course-feishu/handbook-152.jpg",
    "assets/image-course-feishu/handbook-153.jpg",
    "assets/image-course-feishu/handbook-154.jpg",
    "assets/image-course-feishu/handbook-155.jpg",
    "assets/image-course-feishu/handbook-156.jpg",
    "assets/image-course-feishu/handbook-157.jpg",
    "assets/image-course-feishu/handbook-158.jpg",
    "assets/image-course-feishu/handbook-159.jpg",
    "assets/image-course-feishu/handbook-160.jpg",
    "assets/image-course-feishu/handbook-161.jpg",
    "assets/image-course-feishu/handbook-162.jpg",
    "assets/image-course-feishu/handbook-163.jpg",
    "assets/image-course-feishu/handbook-164.jpg",
    "assets/image-course-feishu/handbook-165.jpg",
    "assets/image-course-feishu/handbook-166.jpg",
    "assets/image-course-feishu/handbook-167.jpg",
    "assets/image-course-feishu/handbook-168.jpg",
    "assets/image-course-feishu/handbook-169.jpg",
    "assets/image-course-feishu/handbook-170.jpg",
    "assets/image-course-feishu/handbook-171.jpg",
    "assets/image-course-feishu/handbook-172.jpg",
    "assets/image-course-feishu/handbook-173.jpg",
    "assets/image-course-feishu/handbook-174.jpg",
    "assets/image-course-feishu/handbook-175.jpg",
    "assets/image-course-feishu/handbook-176.jpg",
    "assets/image-course-feishu/handbook-177.jpg",
    "assets/image-course-feishu/handbook-178.jpg",
    "assets/image-course-feishu/handbook-179.jpg",
    "assets/image-course-feishu/handbook-180.jpg",
    "assets/image-course-feishu/handbook-181.jpg",
    "assets/image-course-feishu/handbook-182.png",
    "assets/image-course-feishu/handbook-183.png",
    "assets/image-course-feishu/handbook-184.png",
    "assets/image-course-feishu/handbook-185.png",
    "assets/image-course-feishu/handbook-186.png",
    "assets/image-course-feishu/handbook-187.jpg",
    "assets/image-course-feishu/handbook-188.jpg",
    "assets/image-course-feishu/handbook-189.png",
    "assets/image-course-feishu/handbook-190.png",
    "assets/image-course-feishu/handbook-191.png",
    "assets/image-course-feishu/handbook-192.png",
    "assets/image-course-feishu/handbook-193.jpg",
    "assets/image-course-feishu/handbook-194.jpg",
    "assets/image-course-feishu/handbook-195.png",
    "assets/image-course-feishu/handbook-196.png",
    "assets/image-course-feishu/handbook-197.png",
    "assets/image-course-feishu/handbook-198.jpg",
    "assets/image-course-feishu/handbook-199.png",
    "assets/image-course-feishu/handbook-200.png",
    "assets/image-course-feishu/handbook-201.png",
    "assets/image-course-feishu/handbook-202.png",
    "assets/image-course-feishu/handbook-203.png",
    "assets/image-course-feishu/handbook-204.png",
    "assets/image-course-feishu/handbook-205.jpg",
    "assets/image-course-feishu/handbook-206.jpg",
    "assets/image-course-feishu/handbook-207.png",
    "assets/image-course-feishu/handbook-208.jpg",
    "assets/image-course-feishu/handbook-209.png",
    "assets/image-course-feishu/handbook-210.jpg",
    "assets/image-course-feishu/handbook-211.png",
    "assets/image-course-feishu/handbook-212.png",
    "assets/image-course-feishu/handbook-213.png",
    "assets/image-course-feishu/handbook-214.jpg",
    "assets/image-course-feishu/handbook-215.png",
    "assets/image-course-feishu/handbook-216.png",
    "assets/image-course-feishu/handbook-217.png",
    "assets/image-course-feishu/handbook-218.png",
    "assets/image-course-feishu/handbook-219.png",
    "assets/image-course-feishu/handbook-220.png",
    "assets/image-course-feishu/handbook-221.png",
    "assets/image-course-feishu/handbook-222.png",
    "assets/image-course-feishu/handbook-223.png",
    "assets/image-course-feishu/handbook-224.png",
    "assets/image-course-feishu/handbook-225.jpg",
    "assets/image-course-feishu/handbook-226.png",
    "assets/image-course-feishu/handbook-227.jpg",
    "assets/image-course-feishu/handbook-228.jpg",
    "assets/image-course-feishu/handbook-229.png",
    "assets/image-course-feishu/handbook-230.png",
    "assets/image-course-feishu/handbook-231.png",
    "assets/image-course-feishu/handbook-232.png",
    "assets/image-course-feishu/handbook-233.png",
    "assets/image-course-feishu/handbook-234.png"
  ],
  "lesson1": [
    "assets/image-course-feishu/lesson1-01.png",
    "assets/image-course-feishu/lesson1-02.png",
    "assets/image-course-feishu/lesson1-03.png",
    "assets/image-course-feishu/lesson1-04.png",
    "assets/image-course-feishu/lesson1-05.png",
    "assets/image-course-feishu/lesson1-06.png",
    "assets/image-course-feishu/lesson1-07.png",
    "assets/image-course-feishu/lesson1-08.png",
    "assets/image-course-feishu/lesson1-09.png",
    "assets/image-course-feishu/lesson1-10.png"
  ],
  "lesson2": [
    "assets/image-course-feishu/lesson2-01.png",
    "assets/image-course-feishu/lesson2-02.png",
    "assets/image-course-feishu/lesson2-03.png",
    "assets/image-course-feishu/lesson2-04.png",
    "assets/image-course-feishu/lesson2-05.png",
    "assets/image-course-feishu/lesson2-06.png",
    "assets/image-course-feishu/lesson2-07.png",
    "assets/image-course-feishu/lesson2-08.png",
    "assets/image-course-feishu/lesson2-09.png",
    "assets/image-course-feishu/lesson2-10.png",
    "assets/image-course-feishu/lesson2-11.png"
  ],
  "lesson3": [
    "assets/image-course-feishu/lesson3-01.png",
    "assets/image-course-feishu/lesson3-02.png",
    "assets/image-course-feishu/lesson3-03.png",
    "assets/image-course-feishu/lesson3-04.png",
    "assets/image-course-feishu/lesson3-05.png",
    "assets/image-course-feishu/lesson3-06.png",
    "assets/image-course-feishu/lesson3-07.png",
    "assets/image-course-feishu/lesson3-08.png",
    "assets/image-course-feishu/lesson3-09.png",
    "assets/image-course-feishu/lesson3-10.png",
    "assets/image-course-feishu/lesson3-11.png",
    "assets/image-course-feishu/lesson3-12.png",
    "assets/image-course-feishu/lesson3-13.png",
    "assets/image-course-feishu/lesson3-14.png",
    "assets/image-course-feishu/lesson3-15.png",
    "assets/image-course-feishu/lesson3-16.png",
    "assets/image-course-feishu/lesson3-17.png",
    "assets/image-course-feishu/lesson3-18.png",
    "assets/image-course-feishu/lesson3-19.png",
    "assets/image-course-feishu/lesson3-20.png"
  ],
  "lesson4": [
    "assets/image-course-feishu/lesson4-01.png",
    "assets/image-course-feishu/lesson4-02.png",
    "assets/image-course-feishu/lesson4-03.png",
    "assets/image-course-feishu/lesson4-04.png",
    "assets/image-course-feishu/lesson4-05.png",
    "assets/image-course-feishu/lesson4-06.png",
    "assets/image-course-feishu/lesson4-07.png",
    "assets/image-course-feishu/lesson4-08.png",
    "assets/image-course-feishu/lesson4-09.png",
    "assets/image-course-feishu/lesson4-10.png",
    "assets/image-course-feishu/lesson4-11.png",
    "assets/image-course-feishu/lesson4-12.png",
    "assets/image-course-feishu/lesson4-13.png",
    "assets/image-course-feishu/lesson4-14.png",
    "assets/image-course-feishu/lesson4-15.jpg",
    "assets/image-course-feishu/lesson4-16.jpg",
    "assets/image-course-feishu/lesson4-17.jpg",
    "assets/image-course-feishu/lesson4-18.png",
    "assets/image-course-feishu/lesson4-19.png",
    "assets/image-course-feishu/lesson4-20.png",
    "assets/image-course-feishu/lesson4-21.png"
  ],
  "lesson5": [
    "assets/image-course-feishu/lesson5-001.png",
    "assets/image-course-feishu/lesson5-002.png",
    "assets/image-course-feishu/lesson5-003.png",
    "assets/image-course-feishu/lesson5-004.png",
    "assets/image-course-feishu/lesson5-005.png",
    "assets/image-course-feishu/lesson5-006.png",
    "assets/image-course-feishu/lesson5-007.png"
  ],
  "lesson6": [
    "assets/image-course-feishu/lesson6-001.jpg",
    "assets/image-course-feishu/lesson6-002.jpg",
    "assets/image-course-feishu/lesson6-003.jpg",
    "assets/image-course-feishu/lesson6-004.jpg",
    "assets/image-course-feishu/lesson6-005.jpg",
    "assets/image-course-feishu/lesson6-006.png",
    "assets/image-course-feishu/lesson6-007.png",
    "assets/image-course-feishu/lesson6-008.png",
    "assets/image-course-feishu/lesson6-009.png",
    "assets/image-course-feishu/lesson6-010.png",
    "assets/image-course-feishu/lesson6-011.png",
    "assets/image-course-feishu/lesson6-012.png",
    "assets/image-course-feishu/lesson6-013.png",
    "assets/image-course-feishu/lesson6-014.png",
    "assets/image-course-feishu/lesson6-015.png",
    "assets/image-course-feishu/lesson6-016.png",
    "assets/image-course-feishu/lesson6-017.png",
    "assets/image-course-feishu/lesson6-018.png",
    "assets/image-course-feishu/lesson6-019.png",
    "assets/image-course-feishu/lesson6-020.png",
    "assets/image-course-feishu/lesson6-021.png",
    "assets/image-course-feishu/lesson6-022.png",
    "assets/image-course-feishu/lesson6-023.png",
    "assets/image-course-feishu/lesson6-024.png",
    "assets/image-course-feishu/lesson6-025.png",
    "assets/image-course-feishu/lesson6-026.png",
    "assets/image-course-feishu/lesson6-027.png",
    "assets/image-course-feishu/lesson6-028.png",
    "assets/image-course-feishu/lesson6-029.png",
    "assets/image-course-feishu/lesson6-030.png",
    "assets/image-course-feishu/lesson6-031.png",
    "assets/image-course-feishu/lesson6-032.png",
    "assets/image-course-feishu/lesson6-033.png",
    "assets/image-course-feishu/lesson6-034.png",
    "assets/image-course-feishu/lesson6-035.png",
    "assets/image-course-feishu/lesson6-036.png",
    "assets/image-course-feishu/lesson6-037.png",
    "assets/image-course-feishu/lesson6-038.png",
    "assets/image-course-feishu/lesson6-039.png",
    "assets/image-course-feishu/lesson6-040.png",
    "assets/image-course-feishu/lesson6-041.png",
    "assets/image-course-feishu/lesson6-042.png",
    "assets/image-course-feishu/lesson6-043.png",
    "assets/image-course-feishu/lesson6-044.png",
    "assets/image-course-feishu/lesson6-045.png",
    "assets/image-course-feishu/lesson6-046.png",
    "assets/image-course-feishu/lesson6-047.png",
    "assets/image-course-feishu/lesson6-048.png",
    "assets/image-course-feishu/lesson6-049.png",
    "assets/image-course-feishu/lesson6-050.png",
    "assets/image-course-feishu/lesson6-051.png",
    "assets/image-course-feishu/lesson6-052.png",
    "assets/image-course-feishu/lesson6-053.png",
    "assets/image-course-feishu/lesson6-054.png",
    "assets/image-course-feishu/lesson6-055.png",
    "assets/image-course-feishu/lesson6-056.png",
    "assets/image-course-feishu/lesson6-057.png",
    "assets/image-course-feishu/lesson6-058.png",
    "assets/image-course-feishu/lesson6-059.png",
    "assets/image-course-feishu/lesson6-060.png",
    "assets/image-course-feishu/lesson6-061.png",
    "assets/image-course-feishu/lesson6-062.png",
    "assets/image-course-feishu/lesson6-063.png",
    "assets/image-course-feishu/lesson6-064.png",
    "assets/image-course-feishu/lesson6-065.png",
    "assets/image-course-feishu/lesson6-066.png",
    "assets/image-course-feishu/lesson6-067.png",
    "assets/image-course-feishu/lesson6-068.png",
    "assets/image-course-feishu/lesson6-069.png",
    "assets/image-course-feishu/lesson6-070.png",
    "assets/image-course-feishu/lesson6-071.png"
  ]
}

const media = (group, index) => imageCourseMedia[group]?.[index - 1]
const mediaExamples = (group, type, prefix, prompt, takeaway) => (imageCourseMedia[group] || []).map((image, index) => ({
  title: `${prefix} ${String(index + 1).padStart(2, '0')}`,
  type,
  image,
  prompt,
  takeaway,
}))

const lesson = (title, lead, sections, caseTitle, caseSteps, output) => ({ title, lead, sections, caseTitle, caseSteps, output })

export const imageCourseStats = [
  ['9', '课程节点'],
  ['377', '原课示例图'],
  ['100+', '可复用 Prompt'],
  ['4', '周训练周期'],
]

export const imageCourseGroups = [
  {
    part: '开营 · 先跑通工具与目标', range: '00', summary: '先明确工具、学习方式和训练目标，再开始做第一张图。',
    chapters: [
      { number: '00', title: '开营仪式：AI生图训练营怎么学', time: '20 分钟', level: '学习导航', intro: '认识课程交付方式、可选工具和 6 节主课的学习顺序；先完成一个小作品，再逐步进入商业场景。', exercise: '选定一个自己真实的海报、产品图或知识卡片任务，写下用途、受众和发布平台。', output: '个人练习任务卡', acceptance: '任务有明确用途、受众、比例和完成时间。' },
    ],
  },
  {
    part: '核心能力 · 从会出图到会精修', range: '01—03', summary: '先学功能与提示词，再建立可以直接交付的商业审美和精修流程。',
    chapters: [
      { number: '01', title: '破冰入门：0基础上手 ChatGPT Image', time: '60 分钟', level: '基础功能', intro: '从文生图、图生图、局部修改、改比例、加文字到多轮精修，完成第一条真实商业图片生产流程。', exercise: '用“主题—用途—风格—元素—文字—比例”六步法生成一张自己的课程或活动海报。', output: '第一张可发布海报 + 迭代记录', acceptance: '能说清用途、主体、文字区和比例；至少完成一轮修改。' },
      { number: '02', title: '提示词工程：万能公式与一次成型', time: '75 分钟', level: '提示词结构', intro: '用用途、主题、受众、主体、背景、风格、构图、色彩、文案、比例和限制把模糊要求变成视觉执行单。', exercise: '把“做一张高级茶叶海报”拆成 10 个关键信息，并给客户提供 3 个可选择方向。', output: '十段式视觉 Brief + 三版出图方向', acceptance: '每条 Prompt 至少包含用途、主体、构图、比例和限制。' },
      { number: '03', title: '商业审美与精修：做成可接单作品', time: '75 分钟', level: '商用交付', intro: '不只追求好看，而是让用户 3 秒看懂；用信息层级、主体、品牌统一和交付检查把初稿修到可发布。', exercise: '选择一张初稿，按“构图—信息层级—商业质感—交付细节”完成四步精修。', output: '商用精修前后对比 + 验收表', acceptance: '标题、主体、留白和平台比例均通过检查。' },
    ],
  },
  {
    part: '变现实操 · 从行业需求到客户交付', range: '04—06', summary: '用电商、海报、知识付费、PPT 与真实商单练习，形成可报价、可交付的作品。',
    chapters: [
      { number: '04', title: '行业场景：电商、设计与知识付费', time: '90 分钟', level: '行业实操', intro: '聚焦电商图片、商业设计图、知识付费图文三类刚需，用场景、卖点、比例和报价切入真实交付。', exercise: '选择一个行业，为主图、宣传海报或知识卡片写出完整 Brief，并做两版比例。', output: '行业图片三件套 Brief', acceptance: '每张图有独立用途、核心卖点、平台比例和交付标准。' },
      { number: '05', title: '用 AI 生图做高质量 PPT', time: '70 分钟', level: '演示表达', intro: '先把内容拆成每页单一观点，再用 16:9 画面生成 PPT 视觉素材；同时掌握从展示到私域接单的基本沟通。', exercise: '为一个主题规划 7 页 PPT：背景、定位、方法、案例、报价、沟通与交付。', output: '7 页 PPT 视觉脚本 + 一套课件图', acceptance: '每页只表达一个观点，图文层级清楚，横版比例统一。' },
      { number: '06', title: 'AI实战：交付一套数学知识卡片商单', time: '100 分钟', level: '真实商单', intro: '以小学数学卡片为例，完成总览卡、单知识点卡、批量生成与版本检查，理解客户需求如何变成系列视觉资产。', exercise: '挑一个可验证的知识主题，做 5 张同风格卡片，并记录固定规则与变化项。', output: '5 张系列知识卡 + 变量表', acceptance: '主题准确、视觉一致、单张可读；不把未经核验内容当作知识结论。' },
    ],
  },
  {
    part: '福利附录 · 反推与提示词图册', range: 'A—B', summary: '使用插件反推参考图，再按 20 个图像方向浏览原课的完整提示词图册。',
    chapters: [
      { number: 'A', title: 'PromptCard：从参考图反推提示词', time: '35 分钟', level: '插件实操', intro: '安装 PromptCard，使用右键或框选分析图片；把分析结果改造成自己的 Prompt，而不是复制原图。', exercise: '挑一张有权使用的图片，输出画面事实、保留/替换/删除清单和自己的提示词。', output: '图片分析卡 + 改写 Prompt', acceptance: '不复制原图文字、Logo、人物身份或受保护元素；输出经过人工核验。', plugin: true },
      { number: 'B', title: 'GPT Image 提示词精选手册', time: '持续练习', level: '案例图册', intro: '按海报、UI、摄影、信息图、漫画、游戏、插画、品牌、PPT 等 20 个方向浏览原课图册，拆解并改写为自己的任务。', exercise: '每周选 3 张原课示例：先写画面结构，再替换主题、产品或受众，生成自己的版本。', output: '每周 3 组参考图改写记录', acceptance: '保留原图来源与分析笔记，能说明自己替换了什么、为什么替换。' },
    ],
  },
]

export const imageCoursePrompts = [
  { label: '十段式视觉 Brief', prompt: '你是一名商业视觉设计师。请为【目标受众】设计一张【图片用途】。主题是【主题】，核心卖点是【卖点1、卖点2、卖点3】。主体为【主体】，背景为【场景】，风格为【风格】，色彩为【颜色】。构图采用【构图】，重点突出【最重要信息】。文字包括【主标题】【副标题】【标签】。比例【比例】，发布在【平台】。要求文字清晰、主体突出、层级分明；不要杂乱、变形、多余人物或无法确认的品牌元素。' },
  { label: '参考图反推', prompt: '先把参考图拆成可观察事实：主体、构图、镜头、光线、材质、色彩、背景、文字留白和比例。再分别输出保留/替换/删除清单，改写成用于【用途】的中文提示词、英文提示词和负面约束。不能确认的内容标记“待核验”；不要复制原图文字、Logo、人物身份或独特角色。' },
]

export const imagePromptRules = [
  ['先写用途', '先说明图片用于海报、封面、主图、知识卡还是 PPT，再决定比例和信息密度。'],
  ['把需求写成执行单', '主体、背景、构图、色彩、文案、平台和限制比单纯堆“高级感”更重要。'],
  ['先初稿，再精修', '第一轮选方向；第二轮只改一个变量，例如标题、光线、比例或背景。'],
  ['文字和版权要人工验收', '模型生成的文字、二维码、品牌、人物和知识内容都要逐项核验。'],
]

const promptCardPrompt = `请把下面这份图片分析结果改写成可执行的生图提示词。\n\n用途：用于【平台/场景】\n目标：保留参考图的【构图/光线/材质/氛围】，但不要复制原图中的【文字、Logo、人物身份或受保护元素】。\n输出：中文提示词、英文提示词、负面约束、待核验风险和建议比例。\n\n图片分析结果：\n【粘贴 PromptCard 输出】`

const sharedRules = imagePromptRules

export const imageCourseChapterContent = {
  '00': {
    prompts: [{ label: '练习任务卡', prompt: '我想做一张【海报/产品图/知识卡片】。用途是【发布平台】，受众是【谁】，希望对方看到后【做什么】。请先不要出图，帮我补全主体、卖点、比例、文字区、参考素材和验收标准，输出一张任务卡。' }], rules: sharedRules,
    caseTitle: '开营第一件事：不从“风格词”开始', caseSummary: '先把一个真实任务写成可执行的出图 Brief，后续每一节都围绕它迭代。', steps: ['确定真实用途与发布平台。', '列出受众、核心卖点、必须出现和不能出现的内容。', '确定比例、素材来源与完成标准。'], examples: [], acceptance: '任务卡能被另一个人直接理解并执行。',
  },
  '01': {
    prompts: [{ label: '课程海报', prompt: '请生成一张竖版课程宣传海报，主题是【课程名】。目标受众是【受众】，画面主体包括【主体元素】，背景为【环境】，整体风格【风格】，主色【颜色】。文字包括【主标题】【副标题】【3 个卖点】；右下角保留 1:1 二维码留白，比例 9:16，文字清晰、商业感强，不要杂乱。' }, { label: '电商主图', prompt: '请生成一张【产品】电商主图。产品占画面中心，突出【卖点】，背景【场景】，风格【风格】，文字为【主促销语】，比例 1:1，产品真实、包装准确、购买欲强、不要多余文字。' }], rules: sharedRules,
    caseTitle: '从第一张图开始：海报、主图与商用案例', caseSummary: '原课用课程海报、电商主图、影视海报、装修对比和建筑概念图演示“需求表达 → 初稿 → 再追问”。', steps: ['先按六步写清主题、用途、风格、元素、文字和比例。', '生成初稿后，单独追问标题、二维码区域或卖点标签。', '保存可用图片到案例库，为后续真实交付准备。'], examples: mediaExamples('lesson1', '第 1 课原图', '基础功能案例', '按本章六步法改写为自己的任务。', '观察用途、主体和比例如何共同决定画面。'), acceptance: '完成一张初稿和一轮有明确目的的修改。',
  },
  '02': {
    prompts: [{ label: '万能公式', prompt: imageCoursePrompts[0].prompt }, { label: '客户需求补全', prompt: '你是一名商业设计顾问。客户说：“【客户原话】”。请先不要生成图片，帮我提出受众、用途、风格、场景、文案、比例、卖点、价格、品牌调性和交付格式这 10 个确认问题，再给出 3 个不同方向的出图方案。' }], rules: sharedRules,
    caseTitle: '从茶叶海报到小红书封面：提示词有结构才可控', caseSummary: '原课通过茶叶三种视觉方向、小红书封面、建筑方案、漫画和招聘海报，演示用途和构图怎样减少废图。', steps: ['先把模糊需求转成 10 个模块。', '让 AI 给出 3 个方向，和客户做选择题而非判断题。', '选择一个方向后再做构图、标题和标签的单变量优化。'], examples: mediaExamples('lesson2', '第 2 课原图', '提示词工程案例', '套用十段式 Prompt，先给出画面 Brief。', '提示词不是越长越好，而是信息完整、层级明确。'), acceptance: '写出一条包含 10 个模块中至少 5 项的可执行 Prompt。',
  },
  '03': {
    prompts: [{ label: '商用精修', prompt: '请基于这张图进行商用级精修，不改变主题和主体：提升商业质感；主标题更醒目；减少背景干扰并增加留白；统一色彩和字体；检查文字、边距、二维码区域、人物手部和产品变形；适合【平台】，保持【比例】。' }, { label: '知识卡片', prompt: '根据以下内容制作一张知识核心卡片，主题【主题】，受众【受众】，只保留【数量】个要点；标题醒目、正文易读、背景干净、轻微装饰，比例【比例】，生成前先检查是否信息过载。' }], rules: sharedRules,
    caseTitle: '从“好看”到“可发布”：课程海报、产品图与知识卡', caseSummary: '原课将一张课程海报连续精修，并展示香薰产品、读书笔记、社群干货、APP UI 与艺术海报的交付逻辑。', steps: ['先挑构图方向，不在初稿阶段纠结细节。', '按标题、卖点、主体、背景逐项调整信息层级。', '最后检查比例、文字、留白、品牌、版权和文件版本。'], examples: mediaExamples('lesson3', '第 3 课原图', '精修与商用案例', '先做初稿，再只改一个变量完成精修。', '“能直接发”比“元素越多越炫”更接近真实商业需求。'), acceptance: '输出精修前后对比并写明每次改动的原因。',
  },
  '04': {
    prompts: [{ label: '电商主图', prompt: '请为【产品】生成电商平台主图。主体【产品外观/包装】放在【场景】中，突出【3 个卖点】；风格【风格】，主色【颜色】，文字【品牌/促销语/核心卖点】，比例 1:1，产品突出、真实、有购买欲。' }, { label: '活动海报', prompt: '请设计一张【活动类型】宣传海报，主题【主题】，目标人群【人群】，主体元素【元素】，风格【风格】，主色【颜色】。文字含标题、时间、地点和 3 个亮点，二维码区域留白，比例【比例】，适合社群和朋友圈。' }], rules: sharedRules,
    caseTitle: '三类刚需图：电商、商业设计与知识付费', caseSummary: '原课包含床品详情页、线下 AI 沙龙、城市文旅、公益海报、数码 Banner、电商套图和包装设计商单。', steps: ['选择一类真实行业任务，先写用途、卖点、平台比例和交付版本。', '主图、详情页、活动海报或知识卡片各自只承担一个任务。', '需要套图时先固定色板、产品、光线和留白，再替换主题。'], examples: mediaExamples('lesson4', '第 4 课原图', '行业场景案例', '用行业模板替换产品、卖点和受众后再生成。', 'AI 生图变现的关键是理解场景和客户的发布问题。'), acceptance: '完成一张主图与一张适配不同平台的延展版本。',
  },
  '05': {
    prompts: [{ label: 'PPT 视觉脚本', prompt: '请把主题【主题】规划为 7 页 16:9 PPT。每页只表达一个观点，分别写出页面标题、核心内容、画面主体、色彩和排版结构；再为每页生成一条无长文、可作为 PPT 底图的生图 Prompt。' }, { label: '客户需求单', prompt: '你是一名 AI 商业图片接单顾问。请根据客户原话整理成图片设计需求单：图片用途、目标受众、核心卖点、必须出现的文字、风格方向、比例尺寸、交付版本、修改范围、截止时间和待确认问题。客户原话：【粘贴】' }], rules: sharedRules,
    caseTitle: '把内容变成 16:9 视觉课件，再用它完成私域展示', caseSummary: '原课用“接单变现+私域引流”示范 7 页 PPT 图，并给出朋友圈、社群、低门槛产品和接单五问。', steps: ['先把内容分成单页单观点，避免一页塞满长文。', '用统一色板与版式生成一组 16:9 视觉底图。', '交付前补齐文字排版、来源、版本和客户需求单。'], examples: mediaExamples('lesson5', '第 5 课原图', 'PPT 与接单案例', '先写 7 页视觉脚本，再生成每页底图。', 'PPT 生图不是替代内容结构，而是把观点做成可读画面。'), acceptance: '完成至少 5 页同风格 16:9 课件图，并能解释每页的阅读重点。',
  },
  '06': {
    prompts: [{ label: '系列知识卡', prompt: '请为【学科/主题】生成【数量】张系列知识卡。固定规则：主色【色彩】、插画风格【风格】、标题位置【位置】、角色/图标【元素】、比例【比例】；每张只改变【知识点】。先输出系列规范和每张卡的内容校验清单，再生成。' }, { label: '知识准确性检查', prompt: '请审校下面这张知识卡的文字：逐条列出可验证事实、可能错误/歧义、需要补来源的内容和适合三年级学生的改写建议。不要补造教材结论。内容：【粘贴】' }], rules: sharedRules,
    caseTitle: '真实客户练习：小学数学知识卡片批量交付', caseSummary: '原课从“长方形和正方形”开始，扩展到时分秒、加减法、测量、倍数、乘法、分数等 48 个卡片题目和完整原图。', steps: ['先锁定年级、知识点、语言难度、插画风格和卡片比例。', '从一张总览卡开始，逐步扩展为单知识点卡。', '批量生成后并排检查术语、公式、数字、角色一致性与可读性。'], examples: mediaExamples('lesson6', '第 6 课原图', '数学卡片商单', '先固定视觉规则，再逐个替换知识点。', '教育内容必须人工核验，不能把模型生成结果当教材。'), acceptance: '完成 5 张同风格卡片，并保留知识核验记录和版本表。',
  },
  A: {
    prompts: [{ label: '插件结果改写', prompt: promptCardPrompt }], rules: sharedRules,
    caseTitle: 'PromptCard：把灵感图变成可编辑的视觉观察', caseSummary: '原课附录提供了插件入口与操作示例；本节补上版权、隐私、人工核验和改写流程。', steps: ['从 Chrome 商店安装并固定 PromptCard。', '对有权使用的图片做右键或框选分析。', '把分析结果补上用途、受众、比例、限制和验收，再生成自己的版本。'], examples: mediaExamples('appendix1', '附录原图', 'PromptCard 使用示例', promptCardPrompt, '插件结果只是观察草稿，最终 Prompt 必须人工改写。'), acceptance: '保留原图来源、插件输出、改写 Prompt 与生成版本。',
  },
  B: {
    prompts: [{ label: '图册拆解', prompt: '请选择一张参考图，按主体、构图、镜头、光线、材质、色彩、文字区、比例和限制写出 10 条画面事实；再把主题、受众和产品替换成自己的任务，输出新的 Prompt。' }], rules: sharedRules,
    caseTitle: '完整提示词图册：20 个方向、234 张原课示例', caseSummary: '原课图册覆盖海报、UI/UX、摄影、信息图、社交媒体、漫画、游戏、插画、Logo、节日贺卡、3D、PPT、人像、图像编辑与风格迁移等方向。', steps: ['每次只选一张图，先描述事实而不是直接复制。', '列出哪些构图关系要保留、哪些元素必须替换。', '把自己的 Prompt 与生成结果一起记录，形成可检索灵感库。'], examples: mediaExamples('handbook', '提示词手册原图', '精选手册示例', '先完成画面事实拆解，再用于自己的主题。', '这 234 张均来自原课图册；首次只加载前 12 张，按需展开完整图册。'), acceptance: '完成 3 张图的改写记录，清楚标注原图来源和替换项。',
  },
}

export const imageLessonContent = {
  '00': lesson('开营不是看完目录，而是选定一个真实任务', '本课以图文形式学习。先从自己需要发布的一张图开始，后面的提示词、案例和交付方法才能真正被用起来。', [['工具准备', '课程示例主要使用 ChatGPT Image；也可把结构迁移到其他支持对话式生图的平台。', ['先确认账号与平台是否可用。', '不要使用来源不明的镜像站或账户。']], ['学习方法', '每课只完成一个小交付物：任务卡、Prompt、初稿、精修稿或案例复盘。', ['保存每轮 Prompt 与图片。', '遇到真实客户素材先做脱敏和授权确认。']]], '案例：把“想学 AI 生图”改成一张任务卡', ['选择一个真实发布场景。', '写清谁会看、想让对方做什么。', '规定比例、截止时间和验收标准。'], '个人练习任务卡：用途、受众、卖点、比例、素材、验收。'),
  '01': lesson('第一课先建立“图片生产流水线”', 'AI 生图不是只输入一句话，而是从需求表达、生成、修改到交付的一条生产流程。', [['六类功能', '文生图、图生图、局部修改、改比例、版式文字和多轮精修。', ['每次只先解决一个目的。', '不要期望一次生成终稿。']], ['六步表达', '主题、用途、风格、元素、文字、比例。', ['像给设计师下单一样说明需求。', '生成后针对一个问题继续追问。']]], '案例：课程海报与电商主图', ['先写完整需求。', '先生成底图。', '第二轮只调整标题、卖点或留白。'], '第一张可发布图片 + 一轮迭代。'),
  '02': lesson('提示词是视觉执行单', '用结构化信息替代关键词堆砌，让工具理解你要做什么、给谁看、在哪里发布。', [['十个模块', '用途、主题、受众、主体、背景、风格、构图、色彩、文案、平台与限制。', ['长 Prompt 不等于完整 Prompt。', '先写最关键的 5 项。']], ['三方向选择', '先让工具把模糊需求拆成不同视觉方向，再和客户选择。', ['给选择题，避免让客户凭空判断。', '保留每个方向的 Prompt 与结果。']]], '案例：茶叶海报与小红书封面', ['把模糊需求拆成 10 项。', '生成 3 个方向。', '选择一个方向做单变量精修。'], '十段式 Prompt + 三个方向。'),
  '03': lesson('商用级图片必须可读、可发、可验收', '真实客户需要的是能服务于发布和成交的图。精修不是堆特效，而是把信息和品质修到可用。', [['四个标准', '信息清楚、主体明确、风格统一、能直接发布。', ['用户 3 秒看懂主题。', '标题与产品不能互相抢戏。']], ['四步精修', '挑方向、修信息层级、修商业质感、修交付细节。', ['初稿先选构图。', '二维码、错字与边距最后验收。']]], '案例：课程海报、香薰产品与读书笔记卡', ['先选构图。', '再改标题/卖点/背景。', '最后检查文字、比例和版本。'], '商用精修前后对比 + QA。'),
  '04': lesson('先进入有需求、有预算、有复购的场景', '电商、商业设计和知识付费都有稳定的图文需求；关键不是做艺术图，而是解决客户的发布问题。', [['电商图片', '主图、详情页、促销图、直播封面和买家秀氛围图。', ['产品和卖点必须清楚。', '一张图只承担一个转化任务。']], ['商业与知识付费', '活动海报、课程海报、知识卡片、社群分享图与城市品牌图。', ['先固定平台比例。', '再确定标题区、卖点和行动入口。']]], '案例：床品详情页、AI 沙龙与包装设计', ['用模板补全客户需求。', '完成一张主图和一张延展图。', '按版本与修改范围整理交付。'], '行业图片三件套 Brief。'),
  '05': lesson('PPT 先有观点结构，再有视觉素材', 'AI 生图可以让每页更有表达力，但不能替代信息结构；先拆每页观点，再生成统一的横版视觉。', [['7 页脚本', '背景、定位、人群、方法、案例、沟通、交付。', ['一页一个重点。', '16:9 比例与同一色板。']], ['接单沟通', '用朋友圈展示结果，用社群先贡献价值，再用接单五问收集需求。', ['明确用途、受众、文字、风格、截止时间和修改范围。', '先卖小交付物练手。']]], '案例：接单变现与私域引流 PPT', ['先给每页写标题和一句结论。', '生成无长文的视觉底图。', '后期排版并附客户需求单。'], '7 页视觉脚本 + PPT 素材。'),
  '06': lesson('系列知识卡的难点是准确与一致', '真实商单不是出一张好图，而是批量产出一组可读、统一、可复核的教育图文。', [['先定视觉圣经', '固定色板、插画风格、标题位置、比例、角色与禁用元素。', ['把固定规则写进每条 Prompt。', '每张只改知识点。']], ['内容核验', '数学公式、术语和数字必须人工对照可靠资料。', ['模型输出不是教材来源。', '保留校验人、来源和修改记录。']]], '案例：小学数学知识卡片', ['先做单元总览。', '扩展到单知识点。', '并排检查术语、数字与视觉一致性。'], '5 张系列知识卡 + 变量表 + 核验表。'),
  A: lesson('反推参考图是为了做自己的版本', '插件帮助你看懂画面，但最终作品必须改写用途、主题、受众与元素，并遵守版权和隐私边界。', [['安装', '使用 Chrome Web Store 安装 PromptCard 并阅读扩展权限。', ['只分析有权使用的图片。', '不上传未公开客户素材。']], ['改写', '把插件结果补充用途、受众、比例、保留/替换/删除与验收。', ['不复制 Logo、人物身份或原图文字。', '不能确认的内容标记待核验。']]], '案例：把灵感图改造成自己的课程海报', ['先写画面事实。', '替换主题和视觉主体。', '生成后检查版权、文字和品牌。'], '图片分析卡 + 改写 Prompt。'),
  B: lesson('图册是练习素材，不是复制清单', '原课完整图册覆盖 20 个视觉方向。每次挑一张，拆结构、替主题、写 Prompt、做一轮迭代。', [['20 个方向', '海报、UI、摄影、信息图、社交媒体、漫画、游戏、插画、品牌、PPT、人像和图像编辑等。', ['从自己的真实任务选择方向。', '不要一次浏览完就算学会。']], ['每周练习', '一周做 3 组：画面事实、改写 Prompt、自己的结果与复盘。', ['保留来源与参考边界。', '只有自己的任务和修改才算作品。']]], '案例：三张参考图的改写记录', ['描述事实。', '写保留/替换/删除。', '生成自己的版本并记录差异。'], '3 组图册改写记录。'),
}

export const imagePromptCardAppendix = promptCardAppendix

export const imageCourseExamples = []
