export const knowledgeTypes = ['全部', '任务卡', 'Prompt 模板', '操作清单', 'Skill 使用', '案例拆解']

export const knowledgeItems = [
  {
    id: 'task-card-brief', type: '任务卡', title: '把“帮我处理一下”改成可执行任务卡',
    summary: '先写目标、输入、动作、约束、输出和验收，AI 才能稳定交付。', tool: 'WorkBuddy',
    tags: ['任务拆解', 'WorkBuddy', '交付'], author: '武同学', updatedAt: '2026-07-25', useCount: 1248,
    courseId: 'free', courseLabel: 'WorkBuddy 免费实战课 · 第 1 章', chapterNumber: '01', relatedCaseId: 'receipts',
    sections: [
      ['先写结果，不写愿望', '把“帮我做一份报告”改成“基于指定文件，输出一份 5 页管理层简报，保留来源并标出待确认事项”。'],
      ['输入和边界要能检查', '明确使用哪些文件、目录、链接和时间范围；重要文件先复制到演练目录，外部发布和删除动作必须停下来确认。'],
      ['最后写验收标准', '规定格式、数字口径、文件位置、引用来源和必须人工确认的内容，交付时逐项核对。'],
    ],
  },
  {
    id: 'prompt-work-task', type: 'Prompt 模板', title: '办公任务 Prompt：先计划，再小步执行',
    summary: '适合文件整理、报表分析、周报和资料汇总，避免 AI 一上来直接改文件。', tool: 'WorkBuddy',
    tags: ['办公', 'Plan', '安全'], author: '武同学', updatedAt: '2026-07-24', useCount: 986,
    courseId: 'free', courseLabel: 'WorkBuddy 免费实战课 · 第 4 章', chapterNumber: '04', relatedCaseId: 'receipts',
    prompt: '请先阅读任务目录和输入材料，不要修改文件。\n先输出：目标理解、输入清单、执行计划、风险点和验收标准。\n我确认计划后，再分步骤执行，每一步说明变更文件和验证结果。',
    sections: [['适合场景', '第一次处理重要材料、跨多个文件、涉及外部发布或需要保留审计记录的任务。'], ['使用提醒', 'Ask 用来理解和查看，Plan 用来拆解和确认，Craft 用来执行；不要把三个模式混成一句模糊指令。']],
  },
  {
    id: 'checklist-delivery', type: '操作清单', title: 'AI 交付验收清单：内容、格式、来源、风险',
    summary: '交付前检查四层结果，避免“文件生成了但不能用”。', tool: '通用',
    tags: ['验收', '质量', '交付'], author: '武同学', updatedAt: '2026-07-23', useCount: 812,
    courseId: 'free', courseLabel: 'WorkBuddy 免费实战课 · 第 4 章', chapterNumber: '04',
    sections: [['内容正确', '关键数字、姓名、日期、金额、引用和结论是否与原始材料一致；事实和判断是否分开。'], ['格式可用', '文件能打开、表格可筛选、图片不丢失、字体不溢出、文件名和保存位置符合约定。'], ['来源可追溯', '关键结论有来源，外部资料记录链接和访问日期，无法确认的内容明确标注。'], ['风险已停住', '发布、发送、删除、付款、登录和权限变更等动作都经过人工确认。']],
  },
  {
    id: 'skill-install-review', type: 'Skill 使用', title: '安装 Skill 前先看什么：来源、权限、脚本和回滚',
    summary: 'Skill 不是提示词，而是可安装的能力包；安装前要像装软件一样审查。', tool: 'Skill',
    tags: ['Skill', '安全', '安装'], author: '武同学', updatedAt: '2026-07-22', useCount: 768,
    courseId: 'free', courseLabel: 'WorkBuddy 免费实战课 · 第 5 章', chapterNumber: '05',
    sections: [['先看来源', '优先选择官方仓库、明确作者和持续维护的项目；查看安装量不能替代内容审查。'], ['再看权限', '检查是否读写本地文件、执行命令、访问网络或需要环境变量；不清楚时先在测试目录和低权限环境中验证。'], ['最后做回归', '用一个低风险样本做安装、触发、输出和卸载测试，保留版本号和安装命令，出现异常可以回滚。']],
  },
  {
    id: 'knowledge-card', type: '案例拆解', title: '把收藏变成可召回的知识卡片',
    summary: '摘要不是知识库；真正可复用的卡片要保留来源、事实、观点和下一步动作。', tool: 'WorkBuddy / Obsidian',
    tags: ['知识管理', '研究', '复用'], author: '武同学', updatedAt: '2026-07-21', useCount: 721,
    courseId: 'free', courseLabel: 'WorkBuddy 免费实战课 · 第 16 章', chapterNumber: '16',
    sections: [['一张卡片写什么', '标题、来源、适用问题、关键事实、我的判断、反例或限制、下一步动作。'], ['如何避免堆链接', '每张卡只回答一个可复用问题，原文链接作为证据，不能用长篇复制代替自己的结构化判断。'], ['如何让 AI 召回', '统一标签和命名，保留关键词、项目名称和时间，定期合并重复卡片并标记过期内容。']],
  },
  {
    id: 'invoice-case', type: '案例拆解', title: '发票整理为什么要先做核验台账',
    summary: '从图片识别到结构化明细，再经过重复票、缺字段和金额异常检查。', tool: 'WorkBuddy OCR',
    tags: ['财务', 'OCR', '表格'], author: '武同学', updatedAt: '2026-07-20', useCount: 684,
    courseId: 'free', courseLabel: 'WorkBuddy 免费实战课 · 第 22 章', chapterNumber: '22', relatedCaseId: 'receipts',
    sections: [['第一步：提取', '识别发票号码、日期、金额、税额、购买方和销售方，无法确认的字段保留空值，不要猜。'], ['第二步：核验', '按发票号码和金额去重，标记缺失、异常日期、金额不一致和图片模糊项。'], ['第三步：交付', '生成明细表和异常清单，原图与记录保持可追溯，最终报销动作由人工确认。']],
  },
  {
    id: 'briefing-case', type: '案例拆解', title: '每日早报的关键不是总结，而是信息流设计',
    summary: '采集、去重、来源核验、摘要、排序和推送要分成可检查的步骤。', tool: 'WorkBuddy 自动化',
    tags: ['资讯', '自动化', '早报'], author: '柚子同学', updatedAt: '2026-07-19', useCount: 643,
    courseId: 'free', courseLabel: 'WorkBuddy 免费实战课 · 第 28 章', chapterNumber: '28', relatedCaseId: 'briefing',
    sections: [['来源分层', '官方来源用于事实，行业媒体用于背景，社交平台用于发现线索；不同来源不能混成同一可信等级。'], ['去重与排序', '按事件合并重复内容，再按影响、时效、与个人工作的相关性排序。'], ['推送前确认', '先生成草稿和来源列表，确认没有敏感信息、误读和未经证实的结论，再推送。']],
  },
  {
    id: 'image-prompt', type: 'Prompt 模板', title: '生图提示词：主体、构图、材质、光线、验收',
    summary: '把“好看一点”变成可控制的视觉规格，适合电商、海报和内容配图。', tool: 'AI 生图',
    tags: ['生图', '提示词', '视觉'], author: '武同学', updatedAt: '2026-07-18', useCount: 589,
    courseId: 'image', courseLabel: 'AI 生图工作流训练营 · 提示词规范',
    prompt: '请生成一张用于【用途】的【画面类型】，主体是【对象】，核心卖点是【卖点】。\n构图为【构图】，主体占画面【比例】，材质与细节为【材质】；背景为【环境】，光线为【光线】，整体风格为【风格】。\n保留清晰留白区域用于【文字/Logo】，画面比例为【比例】，避免【禁用元素】。',
    sections: [['先写用途', '先决定是商品主图、宣传海报、封面还是社交配图，不同用途决定信息密度和留白。'], ['再写画面规格', '主体、构图、比例、材质、光线、背景和文字区域要分开写，方便迭代和验收。'], ['最后做验收', '检查主体是否准确、比例是否适合发布、文字区域是否干净、系列图是否保持一致。']],
  },
  {
    id: 'job-evidence', type: '任务卡', title: '求职证据库：不要让 AI 把经历写成空话',
    summary: '把课程作业、项目、实习和校园经历整理成可验证的证据，再生成岗位版本。', tool: '求职 AI 课',
    tags: ['求职', '简历', '证据'], author: '武同学', updatedAt: '2026-07-17', useCount: 532,
    courseId: 'career', courseLabel: '大学生求职 AI 课 · 建立个人证据库',
    sections: [['记录事实', '项目背景、你的具体动作、使用的工具、产出文件、时间和协作对象要分开记录。'], ['补证据', '数字、截图、链接、版本、反馈和前后对比都可以作为证据，但不能编造结果。'], ['按岗位重组', '同一段经历针对不同 JD 重新排序重点，保留事实底稿，不复制一份通用简历到所有岗位。']],
  },
  {
    id: 'codex-delivery', type: '操作清单', title: 'Codex 项目交付：读项目、做计划、改小步、跑验证',
    summary: '把 Codex 当工程执行者，而不是代码生成按钮。', tool: 'Codex',
    tags: ['Codex', '开发', '交付'], author: '武同学', updatedAt: '2026-07-16', useCount: 498,
    courseId: 'codex', courseLabel: 'Codex 橙皮书 · 第四篇：标准工作流',
    sections: [['先读项目', '确认技术栈、入口、构建命令、测试命令、约束文件和不能随便改的目录。'], ['小步执行', '先提出方案和计划，再只改一个模块；每次修改后都查看 diff，避免无关重构。'], ['交付前验证', '运行构建、测试和关键路径检查，整理变更摘要、已知风险和下一步建议。']],
  },
  {
    id: 'meeting-action', type: '操作清单', title: '会议纪要转行动台账：决定、待确认、行动项',
    summary: '会议结束后把信息变成责任人、截止时间和验收标准。', tool: 'WorkBuddy',
    tags: ['会议', '项目管理', '协作'], author: '武同学', updatedAt: '2026-07-15', useCount: 466,
    courseId: 'free', courseLabel: 'WorkBuddy 免费实战课 · 第 17 章', chapterNumber: '17',
    sections: [['分类', '已决定的事项、仍待确认的问题、需要执行的行动项必须分开。'], ['补字段', '每项行动都要有负责人、截止时间、输入材料、交付物和验收人。'], ['发出前确认', '涉及承诺、对外发送或敏感信息时，先让会议负责人确认，再发送最终版本。']],
  },
  {
    id: 'skill-distill', type: 'Skill 使用', title: '把一次成功案例蒸馏成 Skill',
    summary: '只保留跨任务仍然成立的判断、步骤、边界和验收，不把一次性细节全塞进去。', tool: 'Skill',
    tags: ['Skill', '蒸馏', '复用'], author: '武同学', updatedAt: '2026-07-14', useCount: 441,
    courseId: 'free', courseLabel: 'WorkBuddy 免费实战课 · 第 30 章', chapterNumber: '30',
    sections: [['提取稳定规则', '找出多个案例中都出现的输入要求、判断顺序、输出结构和失败边界。'], ['写成协议', '用 SKILL.md 说明触发条件、工作流程、输出格式、禁止事项和验收方法。'], ['做反例测试', '至少用一个正常样本和两个容易失败的样本验证 Skill，记录哪里需要继续迭代。']],
  },
  {
    id: 'multi-agent', type: '任务卡', title: '多 Agent 设计：专业分工比角色数量更重要',
    summary: '用研究、执行、审查的明确交接，降低上下文混乱和错误传播。', tool: 'WorkBuddy / Codex',
    tags: ['多 Agent', '工作流', '审查'], author: '武同学', updatedAt: '2026-07-13', useCount: 398,
    courseId: 'free', courseLabel: 'WorkBuddy 免费实战课 · 第 32 章', chapterNumber: '32',
    sections: [['先判断是否需要', '任务足够复杂、需要并行、权限隔离或独立评审时才拆分，不为增加角色而增加角色。'], ['定义交接格式', '每个角色明确输入、输出、证据和失败时的处理方式，不能只写“交给下一个 Agent”。'], ['设置独立审查', '重要结论、代码和对外材料最好有独立检查者，避免一个错误在角色之间重复传播。']],
  },
]
